spring:
  # AWS parameter store configuration
  cloud:
    aws:
      endpoint: http://localhost:4566
      credentials:
        access-key: fake
        secret-key: fake
        profile:
          name: dev
      region:
        static: us-east-1
  config:
    import:
      - optional:aws-parameterstore:/config/${spring.application.name}_${spring.profiles.active}/

  # actuator configuration
#  management:
#    endpoints:
#      enabled-by-default: false
#      web:
#        exposure:
#          include: 'health, env'
#    endpoint:
#      health:
#        enabled: true
#        show-details: always
#      env:
#        enabled: true



