version: "3.8"

services:

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=fake
      - AWS_SECRET_ACCESS_KEY=fake
      - DEFAULT_REGION=us-east-1
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - "${REDIS_VOLUME_DIR_DATA}:/data"
    ports:
      - 6379:6379
  

#networks:
#  ls:
#    name: ls
#    driver: bridge  
    
    
 